# Site settings
author: Reno James
title: [Blog Name Redacted]
header-img: img/home-bg.png
email: renojames19@gmail.com
copyright_name: Reno James
description: > # this means to ignore newlines until "baseurl:"
  I'll have thought of something witty later. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  renojames

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
